#      /$$$$$$        /$$                                                         /$$ /$$$$$$$$
#     /$$__  $$      | $$                                                        | $$| $$_____/
#    | $$  \ $$  /$$$$$$$ /$$    /$$ /$$$$$$  /$$$$$$$   /$$$$$$$  /$$$$$$   /$$$$$$$| $$    /$$   /$$  /$$$$$$  /$$$$$$$   /$$$$$$   /$$$$$$$  /$$$$$$
#    | $$$$$$$$ /$$__  $$|  $$  /$$/|____  $$| $$__  $$ /$$_____/ /$$__  $$ /$$__  $$| $$$$$| $$  | $$ /$$__  $$| $$__  $$ |____  $$ /$$_____/ /$$__  $$
#    | $$__  $$| $$  | $$ \  $$/$$/  /$$$$$$$| $$  \ $$| $$      | $$$$$$$$| $$  | $$| $$__/| $$  | $$| $$  \__/| $$  \ $$  /$$$$$$$| $$      | $$$$$$$$
#    | $$  | $$| $$  | $$  \  $$$/  /$$__  $$| $$  | $$| $$      | $$_____/| $$  | $$| $$   | $$  | $$| $$      | $$  | $$ /$$__  $$| $$      | $$_____/
#    | $$  | $$|  $$$$$$$   \  $/  |  $$$$$$$| $$  | $$|  $$$$$$$|  $$$$$$$|  $$$$$$$| $$   |  $$$$$$/| $$      | $$  | $$|  $$$$$$$|  $$$$$$$|  $$$$$$$
#    |__/  |__/ \_______/    \_/    \_______/|__/  |__/ \_______/ \_______/ \_______/|__/    \______/ |__/      |__/  |__/ \_______/ \_______/ \_______/
########################################################################################################################################################


###############################################################
#        the main name of the plugin (used in title/text)     #
###############################################################

MainName: "&8&l[&b&lAdvanced&f&lFurnace&8&l]"

###############################################################
#      # The language to use in the /language folder          #
#                  Default: english                           #
# List: "english" "french" "dutch" "german" "italian"         #
#       "korean" "norwegian" "russian" "spanish" "turkish"    #
###############################################################
language: "english"

